import "./globals.css";
import Topo from "@/componentes/Topo/index"
import Rodape from "@/componentes/Rodape/index"
import Head  from "next/head"; 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <Head>
        <link
          rel="stylesheet"
          href="https://www.w3schools.com/w3css/4/w3.css"
        />
      </Head>
      <body>
        <Topo />
        {children}
        <Rodape />
      </body>
    </html>
  );
}