import "./globals.css";
import Topo from "@/componentes/Topo/index"
import Rodape from "@/componentes/Rodape/index"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <Topo/>
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
